/**
 * Referral Tree & Rewards System
 * Implements a multi-level referral system with 30%/3%/2% split (like Moby)
 * Tracks referrals, calculates rewards, and manages payouts
 */

interface ReferralConfig {
  level1Percent: number; // 30% - direct referrals
  level2Percent: number; // 3% - referrals of referrals
  level3Percent: number; // 2% - third level
  rewardToken: string; // Token mint for rewards (SOL, USDC, $MOBY, etc.)
  minPayoutAmount: number; // Minimum amount to trigger payout
  payoutIntervalMs: number; // How often to process payouts (e.g., daily)
}

const DEFAULT_CONFIG: ReferralConfig = {
  level1Percent: 30,
  level2Percent: 3,
  level3Percent: 2,
  rewardToken: 'So11111111111111111111111111111111111111112', // SOL
  minPayoutAmount: 0.001, // 0.001 SOL
  payoutIntervalMs: 24 * 60 * 60 * 1000, // Daily
};

interface ReferralUser {
  wallet: string;
  referrer?: string; // Direct referrer's wallet
  level2Referrer?: string; // Referrer's referrer
  level3Referrer?: string; // Third level
  code: string; // Unique referral code
  createdAt: number;
  totalReferrals: number;
  directReferrals: number;
  totalRewardsEarned: number; // In reward token units
  totalRewardsPaid: number;
  pendingRewards: number;
  isActive: boolean;
}

interface ReferralEvent {
  id: string;
  referrerWallet: string;
  referredWallet: string;
  level: 1 | 2 | 3;
  feeAmount: number; // Trading fees generated by referred user
  rewardAmount: number; // Calculated reward
  token: string;
  status: 'pending' | 'paid' | 'failed';
  createdAt: number;
  paidAt?: number;
  txSignature?: string;
}

interface ReferralStats {
  totalUsers: number;
  activeUsers: number;
  totalRewardsDistributed: number;
  totalPendingRewards: number;
  topReferrers: Array<{
    wallet: string;
    totalReferrals: number;
    totalRewardsEarned: number;
  }>;
}

// In-memory storage (in production, use database)
const referralUsers = new Map<string, ReferralUser>();
const referralEvents: ReferralEvent[] = [];
const referralCodeToWallet = new Map<string, string>();

let config: ReferralConfig = { ...DEFAULT_CONFIG };

/**
 * Generate a unique referral code
 */
function generateReferralCode(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}

/**
 * Get or create a referral user
 */
export function getOrCreateReferralUser(wallet: string, referrerCode?: string): ReferralUser {
  const normalizedWallet = wallet.toLowerCase();
  
  let user = referralUsers.get(normalizedWallet);
  if (user) return user;

  // Find referrers from code
  let referrer: string | undefined;
  let level2Referrer: string | undefined;
  let level3Referrer: string | undefined;

  if (referrerCode) {
    const directReferrerWallet = referralCodeToWallet.get(referrerCode.toUpperCase());
    if (directReferrerWallet) {
      referrer = directReferrerWallet;
      
      // Get level 2 referrer (referrer's referrer)
      const directReferrer = referralUsers.get(directReferrerWallet);
      if (directReferrer?.referrer) {
        level2Referrer = directReferrer.referrer;
        
        // Get level 3 referrer
        const level2ReferrerUser = referralUsers.get(level2Referrer);
        if (level2ReferrerUser?.referrer) {
          level3Referrer = level2ReferrerUser.referrer;
        }
      }
    }
  }

  const code = generateReferralCode();
  // Ensure code is unique
  while (referralCodeToWallet.has(code)) {
    // Regenerate if collision
    // In practice, 8 chars from 36 charset = 36^8 combinations, very unlikely collision
  }

  user = {
    wallet: normalizedWallet,
    referrer,
    level2Referrer,
    level3Referrer,
    code,
    createdAt: Date.now(),
    totalReferrals: 0,
    directReferrals: 0,
    totalRewardsEarned: 0,
    totalRewardsPaid: 0,
    pendingRewards: 0,
    isActive: true,
  };

  referralUsers.set(normalizedWallet, user);
  referralCodeToWallet.set(code, normalizedWallet);

  // Update referrer stats
  if (referrer) {
    const referrerUser = referralUsers.get(referrer);
    if (referrerUser) {
      referrerUser.totalReferrals++;
      referrerUser.directReferrals++;
    }
  }

  if (level2Referrer) {
    const level2User = referralUsers.get(level2Referrer);
    if (level2User) {
      level2User.totalReferrals++;
    }
  }

  if (level3Referrer) {
    const level3User = referralUsers.get(level3Referrer);
    if (level3User) {
      level3User.totalReferrals++;
    }
  }

  return user;
}

/**
 * Get referral user by wallet
 */
export function getReferralUser(wallet: string): ReferralUser | undefined {
  return referralUsers.get(wallet.toLowerCase());
}

/**
 * Get referral user by code
 */
export function getReferralUserByCode(code: string): ReferralUser | undefined {
  const wallet = referralCodeToWallet.get(code.toUpperCase());
  if (wallet) {
    return referralUsers.get(wallet);
  }
  return undefined;
}

/**
 * Record a trading fee event and calculate referral rewards
 * @param traderWallet - The wallet that generated the fee
 * @param feeAmount - The fee amount in reward token units (e.g., SOL)
 * @param token - The token mint (default: SOL)
 */
export function recordTradingFee(
  traderWallet: string,
  feeAmount: number,
  token: string = config.rewardToken
): ReferralEvent[] {
  const normalizedWallet = traderWallet.toLowerCase();
  const user = referralUsers.get(normalizedWallet);
  
  if (!user || feeAmount <= 0) {
    return [];
  }

  const events: ReferralEvent[] = [];

  // Level 1: Direct referrer
  if (user.referrer) {
    const rewardAmount = feeAmount * (config.level1Percent / 100);
    if (rewardAmount > 0) {
      const event: ReferralEvent = {
        id: `ref_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        referrerWallet: user.referrer,
        referredWallet: normalizedWallet,
        level: 1,
        feeAmount,
        rewardAmount,
        token,
        status: 'pending',
        createdAt: Date.now(),
      };
      events.push(event);
      
      // Update referrer's pending rewards
      const referrerUser = referralUsers.get(user.referrer);
      if (referrerUser) {
        referrerUser.pendingRewards += rewardAmount;
        referrerUser.totalRewardsEarned += rewardAmount;
      }
    }
  }

  // Level 2: Referrer's referrer
  if (user.level2Referrer) {
    const rewardAmount = feeAmount * (config.level2Percent / 100);
    if (rewardAmount > 0) {
      const event: ReferralEvent = {
        id: `ref_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        referrerWallet: user.level2Referrer,
        referredWallet: normalizedWallet,
        level: 2,
        feeAmount,
        rewardAmount,
        token,
        status: 'pending',
        createdAt: Date.now(),
      };
      events.push(event);
      
      const level2User = referralUsers.get(user.level2Referrer);
      if (level2User) {
        level2User.pendingRewards += rewardAmount;
        level2User.totalRewardsEarned += rewardAmount;
      }
    }
  }

  // Level 3: Third level
  if (user.level3Referrer) {
    const rewardAmount = feeAmount * (config.level3Percent / 100);
    if (rewardAmount > 0) {
      const event: ReferralEvent = {
        id: `ref_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        referrerWallet: user.level3Referrer,
        referredWallet: normalizedWallet,
        level: 3,
        feeAmount,
        rewardAmount,
        token,
        status: 'pending',
        createdAt: Date.now(),
      };
      events.push(event);
      
      const level3User = referralUsers.get(user.level3Referrer);
      if (level3User) {
        level3User.pendingRewards += rewardAmount;
        level3User.totalRewardsEarned += rewardAmount;
      }
    }
  }

  referralEvents.push(...events);
  return events;
}

/**
 * Process pending payouts for a user
 * In production, this would send actual tokens on-chain
 */
export async function processPayout(wallet: string): Promise<{ success: boolean; amount: number; txSignature?: string; error?: string }> {
  const user = referralUsers.get(wallet.toLowerCase());
  if (!user || user.pendingRewards < config.minPayoutAmount) {
    return { success: false, amount: 0, error: 'Insufficient pending rewards or below minimum payout' };
  }

  const amount = user.pendingRewards;
  
  try {
    // TODO: In production, execute on-chain transfer here
    // For now, we'll simulate a successful payout
    const txSignature = `simulated_tx_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    // Update user
    user.pendingRewards = 0;
    user.totalRewardsPaid += amount;
    
    // Update events
    for (const event of referralEvents) {
      if (event.referrerWallet === wallet.toLowerCase() && event.status === 'pending') {
        event.status = 'paid';
        event.paidAt = Date.now();
        event.txSignature = txSignature;
      }
    }

    return { success: true, amount, txSignature };
  } catch (error: any) {
    return { success: false, amount: 0, error: error.message };
  }
}

/**
 * Process all pending payouts (batch)
 */
export async function processAllPayouts(): Promise<{ processed: number; failed: number; totalAmount: number }> {
  let processed = 0;
  let failed = 0;
  let totalAmount = 0;

  for (const user of referralUsers.values()) {
    if (user.pendingRewards >= config.minPayoutAmount) {
      const result = await processPayout(user.wallet);
      if (result.success) {
        processed++;
        totalAmount += result.amount;
      } else {
        failed++;
      }
    }
  }

  return { processed, failed, totalAmount };
}

/**
 * Get referral stats for a user
 */
export function getUserReferralStats(wallet: string): {
  user: ReferralUser | undefined;
  directReferrals: ReferralUser[];
  pendingEvents: ReferralEvent[];
  paidEvents: ReferralEvent[];
} {
  const normalizedWallet = wallet.toLowerCase();
  const user = referralUsers.get(normalizedWallet);
  
  const directReferrals: ReferralUser[] = [];
  for (const u of referralUsers.values()) {
    if (u.referrer === normalizedWallet) {
      directReferrals.push(u);
    }
  }

  const pendingEvents = referralEvents.filter(e => 
    e.referrerWallet === normalizedWallet && e.status === 'pending'
  );

  const paidEvents = referralEvents.filter(e => 
    e.referrerWallet === normalizedWallet && e.status === 'paid'
  );

  return { user, directReferrals, pendingEvents, paidEvents };
}

/**
 * Get global referral statistics
 */
export function getReferralStats(): ReferralStats {
  const users = Array.from(referralUsers.values());
  const activeUsers = users.filter(u => u.isActive);
  
  const totalRewardsDistributed = referralEvents
    .filter(e => e.status === 'paid')
    .reduce((sum, e) => sum + e.rewardAmount, 0);

  const totalPendingRewards = referralEvents
    .filter(e => e.status === 'pending')
    .reduce((sum, e) => sum + e.rewardAmount, 0);

  // Top referrers
  const topReferrers = users
    .sort((a, b) => b.totalRewardsEarned - a.totalRewardsEarned)
    .slice(0, 10)
    .map(u => ({
      wallet: u.wallet,
      totalReferrals: u.totalReferrals,
      totalRewardsEarned: u.totalRewardsEarned,
    }));

  return {
    totalUsers: users.length,
    activeUsers: activeUsers.length,
    totalRewardsDistributed,
    totalPendingRewards,
    topReferrers,
  };
}

/**
 * Update referral configuration
 */
export function updateReferralConfig(newConfig: Partial<ReferralConfig>): void {
  config = { ...config, ...newConfig };
}

/**
 * Get current referral configuration
 */
export function getReferralConfig(): ReferralConfig {
  return { ...config };
}

/**
 * Generate referral link
 */
export function generateReferralLink(wallet: string, baseUrl: string): string {
  const user = getReferralUser(wallet);
  if (!user) return baseUrl;
  return `${baseUrl}?ref=${user.code}`;
}

/**
 * Parse referral code from URL
 */
export function parseReferralCodeFromUrl(url: string): string | null {
  try {
    const urlObj = new URL(url);
    return urlObj.searchParams.get('ref')?.toUpperCase() || null;
  } catch {
    return null;
  }
}

/**
 * Reset all data (for testing)
 */
export function resetReferralSystem(): void {
  referralUsers.clear();
  referralEvents.length = 0;
  referralCodeToWallet.clear();
  config = { ...DEFAULT_CONFIG };
}

// Export types
export type { ReferralConfig, ReferralUser, ReferralEvent, ReferralStats };